### ISSUE TITLE
mousewheel settings not working in safari browser when pinch zoom is performed on touchpad

### ISSUE THREAD

**Issue by balamanoharb** [antvis/X6#1090]
The mousewheel settings is enabled as per the docs. However, on trackpad pinch action it zooms in or zooms out the page itself.

```
mousewheel: {
        enabled: true,
        global: true,
        modifiers: ['ctrl', 'meta'],
}
```

### Expected Behavior

touchpad pinch zoom should be captured at the graph level.

### Current Behavior

Browser default action is applied.

### Possible Solution

No solution at present.

### Steps To Reproduce

[codesanbox link](https://codesandbox.io/s/gs7ek?file=/src/app.tsx:509-613) 

### Additional Context

NA

### Your Environment

- x6: 1.21.5
- OS: macOS Big Sur. Version 11.2.3
- Browser: safari

**Comment by NewByVector** [comment]
Sliding the trackpad with two fingers does not trigger the Wheel event.

**Comment by OpportunityLiu** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures

**Comment by OpportunityLiu** [comment]
Tried with my windows laptop with a PTP touch pad, in Edge.

![image](https://user-images.githubusercontent.com/13471233/135765968-d7011ab2-410a-4cac-beb2-5c9112a0501f.png)

When I use pitch gestures, a `WheelEvent` with `ctrlKey: true` will be fired (Although I didn't press ctrl key at that time)

The second event was triggered by a real mouse wheel.

The issue is that the value of `deltaY` is not read by x6, cause very rapid zoom when use gestures.
