### ISSUE TITLE
使用vue组件渲染节点内容时，如何让节点的宽高等于vue组件本身的宽高

### ISSUE THREAD

**Issue by 565823371556Zsl** [antvis/X6#2964]
### Describe the feature you'd like to request

渲染vue节点的时候，如果注册自定义节点时，不指定宽高，渲染出来后，容纳vue节点内容的foreignObject的宽高就都是1px，这就造成了连接桩的位置全都集中在一点

### Describe the solution you'd like

希望渲染vue节点后，foreignObject的宽高自动被vue节点充满，不需要在注册的时候显示指定宽高

### Describe alternatives you've considered

无

**Comment by 565823371556Zsl** [comment]
> 这个在框架内部是不容易做到的，但是外部可以实现，在节点内部的 vue 组件渲染完成后，获取尺寸，然后 resize 节点。不过还是建议在项目中固定节点宽和高。

谢谢，按你说的问题已解决

**Comment by History-1024** [comment]
您好 我试着写了一下 resize您是怎么用的 方面截个代码图片吗

**Comment by zjydipingxian** [comment]
同问, 方便截个代码片段图片吗

**Comment by History-1024** [comment]
到现在我也没解决 哈哈&nbsp;


不弃不离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月27日(星期二) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/X6] 使用vue组件渲染节点内容时，如何让节点的宽高等于vue组件本身的宽高 (Issue #2964)





 
同问, 方便截个代码片段图片吗

**Comment by zjydipingxian** [comment]
> 您好 我试着写了一下 resize您是怎么用的 方面截个代码图片吗



> 方便截个代码片段图片吗

 方便截个代码片段图片吗

**Comment by zjydipingxian** [comment]
> > 这个在框架内部是不容易做到的，但是外部可以实现，在节点内部的 vue 组件渲染完成后，获取尺寸，然后 resize 节点。不过还是建议在项目中固定节点宽和高。
> 
> 谢谢，按你说的问题已解决

方便截个代码片段图片吗

**Comment by zjydipingxian** [comment]
> 到现在我也没解决 哈哈&nbsp; 不弃不离 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年2月27日(星期二) 上午10:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [antvis/X6] 使用vue组件渲染节点内容时，如何让节点的宽高等于vue组件本身的宽高 (Issue #2964) 同问, 方便截个代码片段图片吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

把高度写死就支持我想做的业务了. 现在就是不想写死

**Comment by History-1024** [comment]
我当时就是写死了
&nbsp;


不弃不离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月27日(星期二) 上午10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/X6] 使用vue组件渲染节点内容时，如何让节点的宽高等于vue组件本身的宽高 (Issue #2964)





  
到现在我也没解决 哈哈&nbsp; 不弃不离 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年2月27日(星期二) 上午10:22 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [antvis/X6] 使用vue组件渲染节点内容时，如何让节点的宽高等于vue组件本身的宽高 (Issue #2964) 同问, 方便截个代码片段图片吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
把高度写死就支持我想做的业务了. 现在就是不想写死
